/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <section className={styles.homepage}>
        <nav className={styles.navbar}>
          <ul className={styles.navlinks}>
            <div className={styles.leftnav}>
              <li className={styles.iamnitesh}>iamnitesh</li>
            </div>
            <div className={styles.rightnav}>
              <li>Home</li>
              <li>About</li>
              <li>Contact</li>
            </div>
          </ul>
        </nav>
        <main className={`${styles.main} ${styles.container}`}>
          <h2>THIS PORTFOLIO PAGE IS UNDER DEVELOPMENT</h2>
        </main>
      </section>

      <footer className={styles.footer}>
        <h3>@copyright</h3>
      </footer>
    </div>
  );
}
